using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using CSharpDisplay = Microsoft.CodeAnalysis.CSharp.SymbolDisplay;

namespace Aspose.Cli.Sdk.Analyzers;

/// <summary>
/// Generates product build metadata from catalog-projected MSBuild properties.
/// </summary>
[Generator]
public sealed class ProductBuildMetadataGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingMetadata = new(
        "APCLI005",
        "Product build metadata is incomplete",
        "Product '{0}' is missing compiler-visible build property '{1}'",
        "Aspose.Cli.ProductDiscovery",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ProductMetadata> metadata =
            context.AnalyzerConfigOptionsProvider.Select(
                static (provider, _) => Read(provider.GlobalOptions));

        context.RegisterSourceOutput(
            metadata,
            static (production, product) => Emit(production, product));
    }

    private static ProductMetadata Read(AnalyzerConfigOptions options)
    {
        string id = Value(options, "AsposeProductId");
        return new ProductMetadata(
            id,
            Value(options, "AsposeProductNamespace"),
            Value(options, "AsposeProductDisplayName"),
            Value(options, "AsposeProductEngineName"),
            Value(options, "AsposeProductSdkPackageId"),
            Value(options, "AsposeProductSdkVersion"));
    }

    private static void Emit(
        SourceProductionContext context,
        ProductMetadata product)
    {
        if (string.IsNullOrWhiteSpace(product.Id))
        {
            return;
        }

        foreach ((string name, string value) in product.RequiredProperties())
        {
            if (!string.IsNullOrWhiteSpace(value))
            {
                continue;
            }
            context.ReportDiagnostic(Diagnostic.Create(
                MissingMetadata,
                Location.None,
                product.Id,
                name));
            return;
        }

        string source = $$"""
            // <auto-generated />
            namespace {{product.Namespace}};

            internal static class ProductBuildMetadata
            {
                internal const string ProductId = {{Literal(product.Id)}};
                internal const string DisplayName = {{Literal(product.DisplayName)}};
                internal const string EngineName = {{Literal(product.EngineName)}};
                internal const string SdkPackageId = {{Literal(product.SdkPackageId)}};
                internal const string SdkVersion = {{Literal(product.SdkVersion)}};
            }
            """;
        context.AddSource(
            "ProductBuildMetadata.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    private static string Value(
        AnalyzerConfigOptions options,
        string property)
        => options.TryGetValue(
            $"build_property.{property}",
            out string? value)
            ? value.Trim()
            : string.Empty;

    private static string Literal(string value)
        => CSharpDisplay.FormatLiteral(value, quote: true);

    private readonly struct ProductMetadata(
        string id,
        string productNamespace,
        string displayName,
        string engineName,
        string sdkPackageId,
        string sdkVersion)
    {
        public string Id { get; } = id;

        public string Namespace { get; } = productNamespace;

        public string DisplayName { get; } = displayName;

        public string EngineName { get; } = engineName;

        public string SdkPackageId { get; } = sdkPackageId;

        public string SdkVersion { get; } = sdkVersion;

        public IEnumerable<(string Name, string Value)> RequiredProperties()
        {
            yield return ("AsposeProductNamespace", Namespace);
            yield return ("AsposeProductDisplayName", DisplayName);
            yield return ("AsposeProductEngineName", EngineName);
            yield return ("AsposeProductSdkVersion", SdkVersion);
        }
    }
}
