using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Aspose.Cli.Sdk.Serialization;

namespace Aspose.Cli.Generated;

/// <summary>Source-generated serialization metadata for Cells contracts.</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, WriteIndented = true)]
[JsonSerializable(typeof(Product.Cells.Contracts.WorkbookInfoResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.CellsPreviewSelector))]
[JsonSerializable(typeof(Product.Cells.Contracts.CellsPreviewHint))]
[JsonSerializable(typeof(Product.Cells.Contracts.WorkbookReadResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.ConvertResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.RenderResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.EditResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.EditVerification))]
[JsonSerializable(typeof(Product.Cells.Contracts.CreateResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.DiffResult))]
[JsonSerializable(typeof(Product.Cells.Contracts.SearchResult))]
[JsonSerializable(typeof(JsonObject))]
[JsonSerializable(typeof(Product.Cells.Contracts.OpsBatch))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetValuesOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetFormulaOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ClearRangeOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.CopyRangeOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.FormatRangeOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.MergeCellsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UnmergeCellsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.InsertRowsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteRowsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.InsertColumnsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteColumnsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ResizeRowsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ResizeColumnsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.AddSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.RenameSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetSheetVisibilityOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.FreezePanesOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.CreateChartOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.CreatePivotOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetPageSetupOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetPrintAreaOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.InsertImageOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.RefreshPivotOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.CreateTableOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetAutoFilterOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SortRangeOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetValidationOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DefineNameOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteNameOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.AddCommentOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.EditCommentOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteCommentOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ProtectSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UnprotectSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.GroupRowsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UngroupRowsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.GroupColumnsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UngroupColumnsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ClearValidationOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.RemoveDuplicatesOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ProtectWorkbookOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UnprotectWorkbookOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetHyperlinkOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.RemoveHyperlinkOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.UpdateChartOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.AddConditionalFormatOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.ClearConditionalFormatsOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.MoveSheetOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetBordersOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetDefaultFontOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetTabColorOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetSheetViewOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.DeleteChartOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.AddSparklineOp))]
[JsonSerializable(typeof(Product.Cells.Contracts.SetActiveSheetOp))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(System.Text.Json.JsonElement))]
internal sealed partial class ProductJsonContext : JsonSerializerContext
{
    internal static ProductJsonDefinition Definition => DefinitionHolder.Value;

    private static class DefinitionHolder
    {
        internal static readonly ProductJsonDefinition Value =
            new(Product.Cells.ProductBuildMetadata.ProductId, Default);
    }
}
