<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Aspose.Cli.Product.Pdf\Aspose.Cli.Product.Pdf.csproj" />
    <ProjectReference Include="..\..\src\Aspose.Cli.Sdk\Aspose.Cli.Sdk.csproj" />
    <ProjectReference Include="..\Aspose.Cli.TestKit\Aspose.Cli.TestKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Aspose.Cli.TestKit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspose.PDF.Drawing" />
  </ItemGroup>
</Project>
